### ISSUE TITLE
[Core] Keycloak Setup isn't Working with Tenants

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#3705]
It seems that Dirigible can't be accessed, when deployed with Keycloak configurations:

<img width="614" alt="Screenshot 2024-04-02 at 20 37 42" src="https://github.com/eclipse/dirigible/assets/4092083/5be05648-053e-427c-a985-2da8034ad28b">

> _**Note:** Also it seems that setting the `DIRIGIBLE_SINGLE_TENANT_MODE_ENABLED` environment variable to `true` doesn't solve the issue_

**Application Log:**

```
2024-04-02 17:30:18.513 [WARN ] [http-nio-8080-exec-5] [background] o.e.d.c.t.t.TenantContextInitFilter - Tried to reach unregistered tenant with host [platform.eu1.dirigible.io]
2024-04-02 17:30:18.589 [WARN ] [http-nio-8080-exec-6] [background] o.e.d.c.t.t.TenantContextInitFilter - Tried to reach unregistered tenant with host [platform.eu1.dirigible.io]
2024-04-02 17:30:18.591 [WARN ] [http-nio-8080-exec-7] [background] o.e.d.c.t.t.TenantContextInitFilter - Tried to reach unregistered tenant with host [platform.eu1.dirigible.io]
2024-04-02 17:30:18.652 [WARN ] [http-nio-8080-exec-8] [background] o.e.d.c.t.t.TenantContextInitFilter - Tried to reach unregistered tenant with host [platform.eu1.dirigible.io]
2024-04-02 17:30:18.977 [WARN ] [http-nio-8080-exec-9] [background] o.e.d.c.s.filter.SecurityFilter - Requested URI [/] is forbidden: No logged in user and no white list constraints
```

**Kubernetes Deployment:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirigible-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirigible-platform
  template:
    metadata:
      labels:
        app: dirigible-platform
    spec:
      containers:
        - name: dirigible-platform
          image: dirigiblelabs/dirigible:10.2.6
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "2"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: spring.profiles.active
              value: keycloak
            - name: DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL
              value: https://auth.eu1.dirigible.io/auth/realms/platform
            - name: DIRIGIBLE_KEYCLOAK_CLIENT_ID
              value: platform
            - name: DIRIGIBLE_HOST
              value: https://platform.eu1.dirigible.io
            - name: DIRIGIBLE_SINGLE_TENANT_MODE_ENABLED
              value: "true"
```

**Comment by iliyan-velichkov** [comment]
@ThuF try to deploy it using the following env varaibles:
```
DIRIGIBLE_MULTI_TENANT_MODE=false
DIRIGIBLE_TRIAL_ENABLED=true
```

**Comment by ThuF** [comment]
@iliyan-velichkov Thanks for the hint! Yes, this is the correct deployment configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirigible-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dirigible-platform
  template:
    metadata:
      labels:
        app: dirigible-platform
    spec:
      containers:
        - name: dirigible-platform
          image: dirigiblelabs/dirigible:10.2.6
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "2"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: spring.profiles.active
              value: keycloak
            - name: DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL
              value: https://auth.eu1.dirigible.io/auth/realms/platform
            - name: DIRIGIBLE_KEYCLOAK_CLIENT_ID
              value: platform
            - name: DIRIGIBLE_HOST
              value: https://platform.eu1.dirigible.io
            - name: DIRIGIBLE_MULTI_TENANT_MODE
              value: "false"
            - name: DIRIGIBLE_TRIAL_ENABLED
              value: "true"
```
